# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea24f28e25f65bf89c7fc61bb33076378e0c5c926aa04a527fdb7272ae71128032dfa93457bfe6bd846d5cd1248157522ca3c1292470ec7324095c066212aa92

test:
  secret_key_base: 54ed2d4bf5d5e998dbcf2e7faaf3700e69a29aee43ef609796a084a665548a270681b04c35477d6ebcd24f67de2cefbd1b0dd5a78ceb4a620c539e634f1cd9aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
